# Generated by Django 5.1.3 on 2024-12-04 14:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
                ('status', models.CharField(choices=[('new', 'never reached'), ('visited', 'after onsite visit'), ('wants', 'wants to buy'), ('dont', 'not willing to buy'), ('bought', 'bought already')], default='new', max_length=10)),
                ('note', models.TextField(null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
